CREATE TABLE schedule(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	phone VARCHAR(15) NOT NULL,
	call_count_min_range INT NOT NULL DEFAULT 0,
	call_count_max_range INT NOT NULL DEFAULT 0,
	is_active INTEGER CHECK ( is_active IN (0,1)) NOT NULL DEFAULT 1,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE KEY(phone)
);